config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_authorized'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :tickets do
    member do
      post 'book'
      delete 'unbook'
    end
  end

  get 'errors/not_authorized', to: 'errors#not_authorized'

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # not authorized

    if user.has_role? :carrier
      can :create, Ticket
      can [:read, :update, :destroy], Ticket do |ticket|
        ticket.users.include?(user)
      end
    else
      can :read, Ticket
      can :book, Ticket
      can :unbook, Ticket do |ticket|
        ticket.users.include?(user)
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :user_tickets, dependent: :destroy
  has_many :users, through: :user_tickets

  validates :departure_date, presence: true
  validates :arrival_date, presence: true
  validates :origin, presence: true
  validates :destination, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }

  validate :departure_date_cannot_be_greater_than_arrival_date

  def departure_date_cannot_be_greater_than_arrival_date
    if departure_date.present? && arrival_date.present? && departure_date > arrival_date
      errors.add(:departure_date, "cannot be greater than arrival date")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :user_tickets
  has_many :tickets, through: :user_tickets

  validates :first_name, presence: true, length: { maximum: 100 }
  validates :last_name, presence: true, length: { maximum: 100 }
  validates :email, presence: true, length: { maximum: 150 }, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/user_ticket.rb
class UserTicket < ApplicationRecord
  belongs_to :user
  belongs_to :ticket
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to errors_not_authorized_path, :alert => exception.message
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_authorized
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @tickets = Ticket.all
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  load_and_authorize_resource

  def index
    @tickets = Ticket.all
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.users << current_user
    if @ticket.save
      redirect_to @ticket
    else
      render :new, status: 422
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])
    if @ticket.update(ticket_params)
      redirect_to @ticket
    else
      render :edit
    end
  end

  def book
    @ticket = Ticket.find(params[:id])
    if current_user.tickets << @ticket
      flash[:notice] = 'Билет успешно забронирован'
    else
      flash[:alert] = 'Не удалось забронировать билет'
    end
    redirect_to edit_user_registration_path
  end
    
  def unbook
      @ticket = Ticket.find(params[:id])
      if current_user.tickets.delete(@ticket)
        flash[:notice] = 'Бронирование билета успешно отменено'
      else
        flash[:alert] = 'Не удалось отменить бронирование билета'
      end
      redirect_to edit_user_registration_path
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
    redirect_to root_path
  end

  private

  def ticket_params
    params.require(:ticket).permit(:departure_date, :arrival_date, :origin, :destination, :price)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # Override default create method
  def create
    super do |user|
      user.add_role Role.find(params[:user][:role_ids]).name
    end
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, role_ids: []])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/home/index.html.erb
<header>
  <% if user_signed_in? %>
    <%= link_to 'Profile', edit_user_registration_path %>
  <% end %>
</header>

<section>
    <%= render 'tickets/index' %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Чет типо название</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/_index.html.erb
<h1>Tickets</h1>

<%= link_to 'New Ticket', new_ticket_path %>

<table>
  <tr>
    <th>Departure</th>
    <th>Arrival</th>
    <th>Origin</th>
    <th>Destination</th>
    <th>Price</th>
    <th colspan="4"></th>
  </tr>

  <% @tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.departure_date %></td>
      <td><%= ticket.arrival_date %></td>
      <td><%= ticket.origin %></td>
      <td><%= ticket.destination %></td>
      <td><%= ticket.price %></td>
      <td><%= link_to 'Show', ticket %></td>
      <% if current_user.has_role? :passenger %>
        <td><%= link_to "Book", book_ticket_path(ticket), method: :post %></td>
      <% else %>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>  
    </tr>
  <% end %>
</table>

app/views/tickets/edit.html.erb
<%= form_with(model: @ticket, local: true) do |form| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :departure_date %>
    <%= form.datetime_select :departure_date %>
  </div>

  <div class="field">
    <%= form.label :arrival_date %>
    <%= form.datetime_select :arrival_date %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', root_path %>

app/views/tickets/new.html.erb
<h2>Create Ticket</h2>

<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :departure_date %><br />
    <%= f.datetime_select :departure_date %>
  </div>

  <div class="field">
    <%= f.label :arrival_date %><br />
    <%= f.datetime_select :arrival_date %>
  </div>

  <div class="field">
    <%= f.label :origin %><br />
    <%= f.text_field :origin %>
  </div>

  <div class="field">
    <%= f.label :destination %><br />
    <%= f.text_field :destination %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit "Create Ticket" %>
  </div>
<% end %>

<%= link_to 'Back', root_path %>

app/views/tickets/show.html.erb
<p>
  <strong>Departure:</strong>
  <%= @ticket.departure_date %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @ticket.arrival_date %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @ticket.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @ticket.destination %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<% if current_user.has_role? :carrier %>
  <%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<% end %>
<%= link_to 'Back', root_path %>